### ISSUE TITLE
Is it possible to manage React as main GUI  ?

### ISSUE THREAD

**Issue by ejabu** [VACLab/WarApp#1]
I liked the idea of Electron.

but I found it offers no code-protection as noted [here](https://discuss.atom.io/t/source-code-protection-via-new-v8-compiler/39533/2)

As I found this repo, is it possible to create full React-based desktop java application ?. And compiled it to machine code with methods you offer. Then send the compiled version to Clients.

So basically no one is able to modify or reuse the React.js code that I write.

Is it possible ?
Thanks.

**Comment by davegotz** [comment]
While using the approach in this repo might help obfuscate the code and make it harder to find, JavaScript code would be shipped with the page and someone focused on accessing your code would be able to do so.  This is in part due to the nature of JavaScript, which is interpreted in your browser and must therefore be shipped as source code.  Packing and minimizing can help make it harder for people to casually access your code, but won't protected it from those that want access.
